# Generated by Django 3.2.1 on 2021-05-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='valor_mes',
            new_name='total',
        ),
    ]
