# Generated by Django 3.2.4 on 2021-06-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_valor_mes_movmensalista_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco_numero',
            field=models.IntegerField(default=1, verbose_name='Numéro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco_rua',
            field=models.CharField(default=1, max_length=200, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
