# Generated by Django 3.2.4 on 2021-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210610_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(default=1, max_length=200, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(default=1, max_length=200, verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
