# Generated by Django 3.2.1 on 2021-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEnvio', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('receber', models.BooleanField()),
            ],
        ),
    ]
